global:
  scrape_interval: 24h
  evaluation_interval: 24h

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'blackbox-https'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093



